apiVersion: v1
kind: Service
metadata:
  name: my-react-svc
spec:
  selector:
    app: react-app
  ports:
    - name: react-port
      protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
